name: frankie holt
favicon: null
layout_spectrum: 0.60933
typography_spectrum: 0.2928
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#2d2d2d'
    - '#808080'
    - '#b3b3b3'
  brandStrength: 0.25
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
